title: 白嫖GitHub Pages
tagline: Your sidekick in using GitHub Pages and blogs
description: 学习通过 GitHub 仓库生成 GitHub Pages 网站。
tags:
  - GitHub
  - GitHub Pages
template:
  name: github-pages-with-jekyll
  repo: github-pages-with-jekyll-template
preferences:
  - type: dropdown
    name: language
    label: 语言
    description: 选择你喜欢的语言
    options:
      - label: 中文
        value: zh

before:
  - type: createIssue
    title: 您好，请点击查看简介
    body: 00_class-introduction-issue.md
steps:
  - title: 生成 GitHub Pages 网站
    description: 使用生成器(づ￣3￣)づ╭❤～biu的生成GitHub Pages网站。
    event: page_build
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: respond
        issue: 1
        with: 01_update-index.md
        data:
          deploymentUrl: '%actions.pagesUrl.data.html_url%'
      - type: updateBranchProtection
  - title: 自定义您的首页
    description: 合并pull request带来的首页更改
    event: pull_request.opened
    link: '{{ repoUrl }}/issues'
    actions:
      - type: gate
        left: '%payload.pull_request.body%'
        required: false
        else:
          type: respond
          with: 02_pull-request-blank.md
      - type: getTree
        action_id: tree
        sha: '%payload.pull_request.head.sha%'
      - type: createReview
        body: 02_merge-pr.md
        event: APPROVE
        data:
          branch: '%payload.pull_request.head.ref%'
      - type: closeIssue
        issue: Welcome
  - title: 合并您的pull request
    description: 合并pull request带来的首页更改 
    event: pull_request.closed
    link: '{{ repoUrl }}/pulls'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: gate
        left: '%payload.pull_request.base.ref%'
        operator: ===
        right: main
      - type: updateBranchProtection
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: createIssue
        action_id: issue
        title: Getting ready to blog
        body: 03_change-theme.md
        data:
          deploymentUrl: '%actions.pagesUrl.data.html_url%'
      - type: respond
        with: 03_merged-pr.md
        data:
          url: '%actions.issue.data.html_url%'
  - title: 定义站点详细信息
    description: 通过配置文件来改变您网站展示信息
    event: pull_request
    link: '{{ repoUrl }}/issues'
    actions:
      - type: gate
        gates:
          - left: '%payload.action%'
            operator: ===
            right: opened
          - left: '%payload.action%'
            operator: ===
            right: synchronize
      - type: gate
        required: false
        left: '%payload.action%'
        operator: '!=='
        right: opened
        else:
          type: closeIssue
          issue: Getting ready to blog
      - type: gate
        required: false
        left: '%payload.pull_request.body%'
        else:
          type: respond
          with: 02_pull-request-blank.md
      - type: getFileContents
        filename: _config.yml
        action_id: file
      - type: gate
        left: '/^theme:\s?minima$/m'
        operator: test
        right: '%actions.file%'
        else:
          type: createReview
          event: REQUEST_CHANGES
          body: 04_wrong-theme.md
      - type: createReview
        event: COMMENT
        body: 04_create-blog-post.md
        data:
          branch: '%payload.pull_request.head.ref%'
          date: '%payload.pull_request.created_at%'
  - title: 创作日志
    description: 通过创建新文件来创作第一篇日志吧 ^_^
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pulls'
    actions:
      - type: getTree
        action_id: tree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      - type: gate
        action_id: directory
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/^_posts/'
      - type: gate
        action_id: filenumber
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/\d{4}-\d{2}-\d{2}/'
      - type: gate
        action_id: post
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/[a-zA-Z]\.md$/'
      - type: gate
        action_id: extension
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/\.md$/'
      - type: gate
        action_id: filename
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/(^|\/)\d{4}-\d{2}-\d{2}-.*\.md$/'
      - type: gate
        every: true
        gates:
          - left: '%actions.directory%'
          - left: '%actions.filenumber%'
          - left: '%actions.post%'
          - left: '%actions.extension%'
          - left: '%actions.filename%'
        else:
          - type: createReview
            body: 05_incorrect-post.md
            event: REQUEST_CHANGES
            data:
              directory: '%actions.directory%'
              filenumber: '%actions.filenumber%'
              post: '%actions.post%'
              extension: '%actions.extension%'
              filename: '%actions.filename%'
      - type: createReview
        body: 05_add-front-matter.md
        event: COMMENT
  - title: 添加日志的描述属性
    description: 通过 YAML 叙述日志的展示标题和其他属性ヽ(^_−)ﾉ
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pulls'
    actions:
      - type: getTree
        action_id: tree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      - type: findInTree
        action_id: file
        tree: '%actions.tree.data.tree%'
        path: '/^_posts\/\d{4}-\d{2}-\d{2}-.*\.md$/'
      - type: getFileContents
        filename: '%actions.file.path%'
        action_id: contents
      - type: gate
        required: false
        action_id: dashes
        left: '/^-{3}[\s\S]+-{3}/'
        operator: test
        right: '%actions.contents%'
      - type: gate
        required: false
        action_id: title
        left: '/^title:\s?["''].+["'']$/m'
        operator: test
        right: '%actions.contents%'
      - type: gate
        required: false
        action_id: date
        left: '/^date:\s?\d{4}-\d{2}-\d{2}/m'
        operator: test
        right: '%actions.contents%'
      - type: gate
        every: true
        gates:
          - left: '%actions.dashes%'
          - left: '%actions.title%'
          - left: '%actions.date%'
        else:
          - type: createReview
            body: 06_incorrect-front-matter.md
            event: REQUEST_CHANGES
            data:
              date: '%actions.date%'
              title: '%actions.title%'
              dashes: '%actions.dashes%'
      - type: removeBranchProtection
      - type: createReview
        body: 06_merge-and-celebrate.md
        event: APPROVE
  - title: 发布第一篇日志
    description: 合并pull request后您的一篇日志将会被发布到GitHub Pages上
    event: pull_request.closed
    link: '{{ repoUrl }}/pulls'
    actions:
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: respond
        with: 07_next-steps.md
        data:
          deploymentUrl: '%actions.pagesUrl.data.html_url%'
